In [215]:
import pandas as pd 
import numpy as np
from Perceptron import Perceptron

In [216]:

from numpy import array
from sklearn.preprocessing import Normalizer
from keras.activations import sigmoid
from keras.losses import mse
from numpy.random import uniform

Hyperparameters

In [217]:
batch_size=2

Dataset

In [218]:
data={'Day 1':[30,40,50,20,15,60],'Day 2':[40,50,20,15,60,70],
      'Day 3':[50,20,15,60,70,50],'Target':[20,15,60,70,50,40]}

In [219]:
dataset=pd.DataFrame(data)

In [220]:
dataset

Day 1  Day 2  Day 3  Target
0     30     40     50      20
1     40     50     20      15
2     50     20     15      60
3     20     15     60      70
4     15     60     70      50
5     60     70     50      40

In [221]:
X=dataset.drop('Target',axis=1)
y=dataset['Target']

In [222]:
X

Day 1  Day 2  Day 3
0     30     40     50
1     40     50     20
2     50     20     15
3     20     15     60
4     15     60     70
5     60     70     50

In [223]:
X_norm = Normalizer(norm='max').fit_transform(X)

In [224]:
X_norm

array([[0.6       , 0.8       , 1.        ],
       [0.8       , 1.        , 0.4       ],
       [1.        , 0.4       , 0.3       ],
       [0.33333333, 0.25      , 1.        ],
       [0.21428571, 0.85714286, 1.        ],
       [0.85714286, 1.        , 0.71428571]])

In [225]:
array(y)

array([20, 15, 60, 70, 50, 40], dtype=int64)

In [226]:
np.reshape(array(y),(1,-1))

array([[20, 15, 60, 70, 50, 40]], dtype=int64)

In [227]:
y_norm=Normalizer(norm='max').fit_transform(np.reshape(array(y),(1,-1)))

In [228]:
y_norm

array([[0.28571429, 0.21428571, 0.85714286, 1.        , 0.71428571,
        0.57142857]])

ANN From Scratch

In [229]:
"""weight_1=array([[.2,.1],[.3,.1],[.2,.1]])
weight_2=array([[.5],[.1]])"""

'weight_1=array([[.2,.1],[.3,.1],[.2,.1]])\nweight_2=array([[.5],[.1]])'

In [230]:
weight_1=uniform(-1,1,(3,2)) #shape 3 by 2
weight_2=uniform(-1,1,(2,1))

In [231]:
"""
w1j w1i
w2j w2i
w3j w3i
"""
weight_1


array([[-0.57518855,  0.00872047],
       [ 0.78282447, -0.5347021 ],
       [ 0.60128929,  0.74863196]])

In [247]:
"""
wik wjk
"""
wik=weight_2[0]
wjk=weight_2[1]
weight_2


array([[ 0.16987129],
       [-0.6016983 ]])

In [249]:
weight_x=[wik,wjk]
weight_x

[array([0.16987129]), array([-0.6016983])]

In [233]:
X_norm[0:batch_size]

array([[0.6, 0.8, 1. ],
       [0.8, 1. , 0.4]])

In [234]:
output_1=X_norm[0:batch_size]@weight_1
output_1

array([[ 0.88243573,  0.32610256],
       [ 0.56318935, -0.22827294]])

In [235]:
from keras.activations import sigmoid
act_output=sigmoid(output_1).numpy()
act_output

array([[0.70732671, 0.58081077],
       [0.63719017, 0.44317829]])

In [236]:
pred_output=act_output@weight_2
pred_output=np.reshape(pred_output,(1,-1))
pred_output

array([[-0.22931835, -0.15841931]])

Mean Squared Error

In [237]:
y_true=y_norm[0][0:batch_size]
y_pred=pred_output
y_true

array([0.28571429, 0.21428571])

In [238]:
#y_true
y_true

array([0.28571429, 0.21428571])

Node K output

In [239]:
yhat=mse(y_true,y_pred).numpy()
yhat
s=(y_true-y_pred)
x=s*s
x.mean()

0.20208382606297365

Compute error at k

In [240]:
target=0.909
derivative=yhat*(1-yhat)
k=(target-yhat)*derivative
k

array([0.11398737])

In [241]:
target=0.909

yderivative=y_true[0]*(1-y_true[0])
#j=(target-y_pred[0])*derivative
j=k*wjk*yderivative
j

array([-0.01399714])

In [242]:
iderivative=y_true[1]*(1-y_true[1])
#j=(target-y_pred[0])*derivative
i=k*wik*iderivative
i

array([0.00326013])

In [243]:
#new weight at j
n=0.3
jwc=wjk+(n*k*yhat)
jwc



array([-0.5947878])

In [244]:
#new weight at i
iwc=wik+(n*k*yhat)
iwc

array([0.17678179])

In [245]:
#new output at K
