In [23]:
import pandas as pd 
import numpy as np

In [24]:

from numpy import array
from sklearn.preprocessing import Normalizer
from keras.activations import sigmoid
from keras.losses import mse
from numpy.random import uniform

ImportError: Traceback (most recent call last):
  File "C:\Users\hp\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow', [dirname(__file__)])
  File "C:\Python310\lib\imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hp\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\__init__.py", line 54, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\hp\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "C:\Users\hp\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
    import _pywrap_tensorflow
ModuleNotFoundError: No module named '_pywrap_tensorflow'


Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.

Hyperparameters

In [9]:
batch_size=2

Dataset

In [10]:
data={'Day 1':[30,40,50,20,15,60],'Day 2':[40,50,20,15,60,70],
      'Day 3':[50,20,15,60,70,50],'Target':[20,15,60,70,50,40]}

In [11]:
dataset=pd.DataFrame(data)

In [12]:
dataset

Day 1  Day 2  Day 3  Target
0     30     40     50      20
1     40     50     20      15
2     50     20     15      60
3     20     15     60      70
4     15     60     70      50
5     60     70     50      40

In [13]:
X=dataset.drop('Target',axis=1)
y=dataset['Target']

In [14]:
X

Day 1  Day 2  Day 3
0     30     40     50
1     40     50     20
2     50     20     15
3     20     15     60
4     15     60     70
5     60     70     50

In [15]:
X_norm = Normalizer(norm='max').fit_transform(X)

In [16]:
X_norm

array([[0.6       , 0.8       , 1.        ],
       [0.8       , 1.        , 0.4       ],
       [1.        , 0.4       , 0.3       ],
       [0.33333333, 0.25      , 1.        ],
       [0.21428571, 0.85714286, 1.        ],
       [0.85714286, 1.        , 0.71428571]])

In [17]:
array(y)

array([20, 15, 60, 70, 50, 40], dtype=int64)

In [18]:
np.reshape(array(y),(1,-1))

array([[20, 15, 60, 70, 50, 40]], dtype=int64)

In [19]:
y_norm=Normalizer(norm='max').fit_transform(np.reshape(array(y),(1,-1)))

In [20]:
y_norm

array([[0.28571429, 0.21428571, 0.85714286, 1.        , 0.71428571,
        0.57142857]])

ANN From Scratch

In [21]:
"""weight_1=array([[.2,.1],[.3,.1],[.2,.1]])
weight_2=array([[.5],[.1]])"""

'weight_1=array([[.2,.1],[.3,.1],[.2,.1]])\nweight_2=array([[.5],[.1]])'

In [22]:
weight_1=uniform(-1,1,(3,2)) #shape 3 by 2
weight_2=uniform(-1,1,(2,1))

In [23]:
weight_1

array([[-0.06226089,  0.94017052],
       [ 0.57801386,  0.17040079],
       [ 0.03827152,  0.43701681]])

In [24]:
X_norm[0:batch_size]

array([[0.6, 0.8, 1. ],
       [0.8, 1. , 0.4]])

In [25]:
output_1=X_norm[0:batch_size]@weight_1
output_1

array([[0.46332607, 1.13743975],
       [0.54351376, 1.09734393]])

In [27]:
from keras.activations import sigmoid
act_output=sigmoid(output_1).numpy()
act_output

ModuleNotFoundError: No module named 'tensorflow'

In [ ]:
pred_output=act_output@weight_2
pred_output=np.reshape(pred_output,(1,-1))

Mean Squared Error

In [ ]:
y_true=y_norm[0][0:batch_size]
y_pred=pred_output

In [ ]:
y_true

In [ ]:
mse(y_true,y_pred).numpy()